services:
  - type: web
    name: boat-buddy-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NEXT_PUBLIC_API_URL
        value: https://gemini-marine-api.onrender.com