import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="bg-wood min-h-screen py-8 px-4">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="text-3xl mb-2">⚓</div>
          <h1 className="text-2xl font-bold" style={{ color: '#F5F0E8', fontFamily: 'Georgia, serif' }}>
            Terms &amp; Conditions
          </h1>
          <p className="text-sm mt-1" style={{ color: '#C68B3A', fontFamily: 'Georgia, serif' }}>
            Boat Buddy by WastedApe
          </p>
        </div>

        <div className="panel p-6" style={{ fontFamily: 'Georgia, serif', color: 'rgba(245,240,232,0.85)', lineHeight: '1.7' }}>
          <p className="text-xs mb-6" style={{ color: 'rgba(245,240,232,0.5)' }}>
            Last updated: July 4, 2026
          </p>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>1. Acceptance of Terms</h2>
            <p className="text-sm mb-3">
              By accessing or using Boat Buddy (&quot;the App&quot;), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the App.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>2. Nature of Service</h2>
            <p className="text-sm mb-3">
              Boat Buddy is an AI-powered marine diagnostic assistant designed to provide general guidance and information about boat maintenance and troubleshooting. The service is provided for <strong>informational purposes only</strong>.
            </p>
            <p className="text-sm">
              The AI responses generated by this App should not be considered professional marine engineering advice, and should not replace the assessment of a licensed marine mechanic or certified professional.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>3. Safety Disclaimer</h2>
            <p className="text-sm mb-3">
              <strong>Your safety and the safety of your passengers are paramount.</strong> Always prioritize safety above any guidance provided by this App.
            </p>
            <p className="text-sm mb-3">
              In case of emergency at sea, contact the US Coast Guard immediately via VHF Channel 16 or call 911. Do not rely on this App in emergency situations.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>4. Limitation of Liability</h2>
            <p className="text-sm mb-3">
              WastedApe and Boat Buddy, its developers, employees, and partners shall not be held liable for any damages, losses, injuries, or expenses arising from:
            </p>
            <ul className="text-sm list-disc ml-5 space-y-1">
              <li>Reliance on information provided by the App</li>
              <li>Any errors or inaccuracies in AI-generated responses</li>
              <li>Actions taken or not taken based on App guidance</li>
              <li>Technical failures, downtime, or data loss</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>5. Privacy &amp; Data</h2>
            <p className="text-sm mb-3">
              Conversations and images submitted to Boat Buddy may be processed by AI services and may be used to improve the service. We do not sell your personal information to third parties.
            </p>
            <p className="text-sm">
              Do not submit sensitive personal or financial information through the chat interface.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>6. User Responsibilities</h2>
            <ul className="text-sm list-disc ml-5 space-y-1">
              <li>You must be 18 years or older to use this App</li>
              <li>You are responsible for the security of your account credentials</li>
              <li>Do not use the App for any illegal or unauthorized purpose</li>
              <li>You agree not to submit harmful, offensive, or misleading content</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>7. Changes to Terms</h2>
            <p className="text-sm">
              WastedApe reserves the right to modify these terms at any time. Continued use of the App after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-lg font-bold mb-3" style={{ color: '#C68B3A' }}>8. Contact</h2>
            <p className="text-sm">
              For questions about these Terms, please contact us through the App&apos;s support channel or visit our website.
            </p>
          </section>

          <div className="mt-8 pt-6 text-center" style={{ borderTop: '1px solid rgba(198,139,58,0.3)' }}>
            <p className="text-xs" style={{ color: 'rgba(245,240,232,0.4)' }}>
              © 2026 WastedApe. All rights reserved.
            </p>
          </div>
        </div>

        <div className="text-center mt-6">
          <Link href="/login" className="btn-primary inline-block">
            ← Back to App
          </Link>
        </div>
      </div>
    </div>
  )
}
